name: Android Kotlin lint

on: [ pull_request]

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      #Check out current repository
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: setup gradle
        uses: /.github/workflows/android_gradle_setup.yml

      #Run ktlint
      - name: Run Linters and Test
        run: ./gradlew ktlint -PautoCorrect=0



