name: Android Kotlin lint

on: [ pull_request]

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/android_gradle_setup.yml
      #Check out current repository

      #Run ktlint
      - name: Run Linters and Test
        run: ./gradlew ktlint -PautoCorrect=0



