name: Android Kotlin lint

on: [ pull_request]

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      #Check out current repository
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Setup gradle
        uses: p2p-org/p2p-wallet-android/tree/develop/.github/workflows/android_gradle_setup.yml

      #Run ktlint
      - name: Run Linters and Test
        run: ./gradlew ktlint -PautoCorrect=0



