name: Android Kotlin lint

on: [ pull_request]

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-gradle

      - name: Run Linters and Test
        run: ./gradlew ktlint -PautoCorrect=0

      - name: Try to get branch name
        run: |
          echo $GITHUB_REF_NAME
          echo $GITHUB_HEAD_REF



