name: Android Kotlin lint test

on: [ pull_request ]

jobs:
  Unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 11 }
      - name: Run unit tests
        run: ./gradlew test