name: Android Kotlin lint test

on: [ pull_request,push ]

jobs:
  Unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 11 }
      - name: Run unit tests
        run: ./gradlew test

  Android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 11 }
      - name: Run android lint
        run: ./gradlew --no-daemon -g /cache ktlint -PautoCorrect=0

