on:
  workflow_call:
    inputs:
      work_name:
        type: string
        required: false

jobs:
  setup_java:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2